const PRODUCTMOCKDATA = [
  {
    product_id: "productid",
    product_option_id: "product_option.id",
    product_name: "product.name",
    product_color: "product_option.color",
    product_size: "# 상품 사이즈",
    quantity: "2",
    product_price: "20000",
    product_company: "product.company.name, # 회사 이름 (보니애가구 배송)",
    product_delivery_type: "배송 타입(업체직접배송..)",
    product_delivery_fee: "# 배송비",
  },
  {
    product_id: "productid",
    product_option_id: "product_option.id",
    product_name: "product.name",
    product_color: "product_option.color",
    product_size: "# 상품 사이즈",
    quantity: "2",
    product_price: "20000",
    product_company: "product.company.name, # 회사 이름 (보니애가구 배송)",
    product_delivery_type: "배송 타입(업체직접배송..)",
    product_delivery_fee: "# 배송비",
  },
  {
    product_id: "productid",
    product_option_id: "product_option.id",
    product_name: "product.name",
    product_color: "product_option.color",
    product_size: "# 상품 사이즈",
    quantity: "2",
    product_price: "20000",
    product_company: "product.company.name, # 회사 이름 (보니애가구 배송)",
    product_delivery_type: "배송 타입(업체직접배송..)",
    product_delivery_fee: "# 배송비",
  },
  {
    product_id: "productid",
    product_option_id: "product_option.id",
    product_name: "product.name",
    product_color: "product_option.color",
    product_size: "# 상품 사이즈",
    quantity: "2",
    product_price: "20000",
    product_company: "product.company.name, # 회사 이름 (보니애가구 배송)",
    product_delivery_type: "배송 타입(업체직접배송..)",
    product_delivery_fee: "# 배송비",
  },
];

export default PRODUCTMOCKDATA;
